spring:
  datasource:
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql:///wqxm?useUnicode=true&charcterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: rabbitmq.qfjava.cn
    port: 8800
